Repository IntelligentNetworkSolutions/IllegalDumpSiteDetectionAndLandfillMonitoring, pull requests merged in 2024-10, with the labels that each got.

#130 fix: fixing bugs in some unit tests
  Tests/MainAppBLTests/Services/MapLayerGroupConfigurationServiceTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/DetectionControllerTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/DetectionIgnoreZonesControllerTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/MapConfigurationControllerTests.cs
  Tests/MainAppMVCTests/ViewModels/LegalLandfillManagementTests/LegalLandfillWasteImportViewModelTests.cs
Labels: bug, new feature

#136 Training configs
  .github/workflows/test_unit_n_integration_gh.yml
  DTOs/Helpers/GeoJsonHelpers.cs
  DTOs/MainApp.BL/TrainingDTOs/TrainedModelDTO.cs
  DTOs/MainApp.BL/TrainingDTOs/TrainedModelStatisticsDTO.cs
  DTOs/MainApp.BL/TrainingDTOs/TrainingEpochMetricsDTO.cs
  DTOs/MainApp.BL/TrainingDTOs/TrainingEpochStepMetricsDTO.cs
  DTOs/MainApp.BL/TrainingDTOs/TrainingRunDTO.cs
  DTOs/MainApp.BL/TrainingDTOs/TrainingRunResultsDTO.cs
  DTOs/MainApp.BL/TrainingDTOs/TrainingRunTrainParamsDTO.cs
  DTOs/ObjectDetection.API/MMDetectionConfiguration.cs
  Entities/TrainingEntities/TrainingRunTrainParams.cs
  MainApp.BL/Interfaces/Services/IMMDetectionConfigurationService.cs
  MainApp.BL/Interfaces/Services/TrainingServices/ITrainedModelService.cs
  MainApp.BL/Interfaces/Services/TrainingServices/ITrainingRunService.cs
  MainApp.BL/Services/DatasetServices/DatasetImagesService.cs
  MainApp.BL/Services/MMDetectionConfigurationsService.cs
  MainApp.BL/Services/TrainingServices/TrainedModelService.cs
  MainApp.BL/Services/TrainingServices/TrainingConfigGenerator.cs
  MainApp.BL/Services/TrainingServices/TrainingRunService.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/AccountController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/TrainedModelsController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/TrainingRunsController.cs
  MainApp.MVC/Infrastructure/Register/ApplicationServicesDependencyContainer.cs
  MainApp.MVC/Infrastructure/Register/InfrastructeServicesDependencyContainer.cs
  MainApp.MVC/Infrastructure/Register/RegisterMMDetectionConfiguration.cs
  MainApp.MVC/Program.cs
  MainApp.MVC/appsettings.Development.json
  MainApp.MVC/appsettings.json
  SD/AuthClaims.cs
  Tests/Fixtures/TestDatabaseFixture.cs
Labels: new feature

#138 feat: detections in ignore zones
  DTOs/MainApp.BL/DetectionDTOs/DetectedDumpSiteDTO.cs
  MainApp.BL/Services/ApplicationSettingsService.cs
  MainApp.BL/Services/DetectionServices/DetectionRunService.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/DetectionController.cs
  MainApp.MVC/Areas/IntranetPortal/Views/Shared/_Sidebar.cshtml
  MainApp.MVC/Views/Shared/Components/HistoricData/Default.cshtml
  MainApp.MVC/appsettings.Development.json
  MainApp.MVC/appsettings.Production.json
  MainApp.MVC/appsettings.Staging.json
  MainApp.MVC/appsettings.json
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/DetectionControllerTests.cs
Labels: bug, new feature

#151 Fix paths
  DTOs/Helpers/GeoJsonHelpers.cs
  DTOs/IdTextDTO.cs
  DTOs/MainApp.BL/DatasetDTOs/DatasetFullIncludeDTO.cs
  DTOs/MainApp.BL/EditDatasetDTO.cs
  DTOs/MainApp.BL/StringBuilderResultDTO.cs
  DTOs/ObjectDetection.API/CocoFormatDTOs/CocoAnnotationDTO.cs
  DTOs/ObjectDetection.API/CocoFormatDTOs/CocoExportResultDTO.cs
  DTOs/ObjectDetection.API/Responses/DetectionRun/DetectionRunProgressResponse.cs
  DTOs/ObjectDetection.API/Responses/DetectionRun/DetectionRunStartedResponse.cs
  Entities/FakeEntity.cs
  Entities/Helpers/GeoJsonHelpers.cs
  MainApp.BL/Interfaces/Services/TrainingServices/ITrainedModelService.cs
  MainApp.BL/Services/DatasetServices/DatasetClassesService.cs
  MainApp.BL/Services/DatasetServices/DatasetService.cs
  MainApp.BL/Services/DetectionServices/DetectionRunService.cs
  MainApp.BL/Services/MMDetectionConfigurationsService.cs
  MainApp.BL/Services/TrainingServices/TrainedModelService.cs
  MainApp.BL/Services/TrainingServices/TrainingConfigGenerator.cs
  MainApp.BL/Services/TrainingServices/TrainingRunService.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/DetectionController.cs
  MainApp.MVC/Areas/IntranetPortal/Views/Detection/CreateDetectionRun.cshtml
  MainApp.MVC/appsettings.Development.json
  MainApp.MVC/appsettings.json
  SD/Helpers/CommonHelper.cs
  Tests/DTOsTests/Helpers/NewtonsoftJsonHelperTests.cs
  Tests/DTOsTests/MainAppBL/DatasetDTOsTests/DatasetFullIncludeDTOTests.cs
  Tests/DTOsTests/ObjectDetectionApi/CocoFormatDTOs/CocoAnnotationDTOTests.cs
  Tests/MainAppBLTests/MMDetectionConfigurationServiceTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/DatasetsControllerTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/DetectionControllerTests.cs
  Tests/SDTests/Helpers/CommonHelperTests.cs
Labels: bug

#152 tests: tests for AppSettingsRepo, IntranetPortalTokensRepo and GeoJso…
  DAL/Repositories/ApplicationSettingsRepository.cs
  DAL/Repositories/DetectionRepositories/DetectionRunsRepository.cs
  DAL/Repositories/IntranetPortalUsersTokenDa.cs
  DTOs/Helpers/GeoJsonHelpers.cs
  Entities/Helpers/GeoJsonHelpers.cs
  Tests/DTOsTests/Helpers/GeoJsonHelpersTests.cs
  Tests/DalTests/Repositories/ApplicationSettingsRepositoryTests.cs
  Tests/DalTests/Repositories/DatasetRepositories/DatasetsRepositoryTests.cs
  Tests/DalTests/Repositories/IntranetPortalUsersTokenDaTests.cs
  Tests/EntitiesTests/Helpers/GeoJsonHelpersTests.cs
Labels: testing

#155 tests: legal landfill managmenet controller and services tests, sched…
  Tests/MainAppBLTests/Services/LegalLandfillPointCloudFileServiceTests.cs
  Tests/MainAppBLTests/Services/LegalLandfillServiceTests.cs
  Tests/MainAppBLTests/Services/LegalLandfillTruckServiceTests.cs
  Tests/MainAppBLTests/Services/LegalLandfillWasteImportServiceTests.cs
  Tests/MainAppBLTests/Services/LegalLandfillWasteTypeServiceTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/DetectionControllerTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/LegalLandfillWasteManagementControllerTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/LegalLandfillsManagementControllerTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/ScheduleRunsControllerTests.cs
Labels: testing

#156 Fix import img path no hard class detection
  MainApp.BL/Services/DatasetServices/DatasetService.cs
  MainApp.BL/Services/DetectionServices/DetectionRunService.cs
  MainApp.BL/Services/TrainingServices/TrainingConfigGenerator.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/DatasetsController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/DetectionController.cs
  MainApp.MVC/Areas/IntranetPortal/Views/Detection/CreateDetectionRun.cshtml
  MainApp.MVC/Areas/IntranetPortal/Views/Shared/_Sidebar.cshtml
  Tests/MainAppBLTests/Services/TrainingServices/TrainingConfigGeneratorTests.cs
Labels: bug, testing

#159 fix: detection input image paths fixed and geo json null check
  DTOs/Helpers/GeoJsonHelpers.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/DetectionController.cs
  MainApp.MVC/Views/Shared/Components/HistoricData/Default.cshtml
Labels: bug

#164 feat: area comparison report ignore zone implementation
  DTOs/MainApp.BL/DetectionDTOs/GroupedDumpSitesListHistoricDataDTO.cs
  MainApp.BL/Interfaces/Services/DetectionServices/IDetectionRunService.cs
  MainApp.BL/Services/DetectionServices/DetectionRunService.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/DetectionController.cs
  MainApp.MVC/Views/Shared/Components/HistoricData/Default.cshtml
  Tests/MainAppBLTests/Services/DetectionRunServiceTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/DetectionControllerTests.cs
Labels: new feature

#169 test: x unit tests for detection, schedule runs, trained models and t…
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/DetectionControllerTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/ScheduleRunsControllerTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/TrainedModelsControllerTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/TrainingRunsControllerTests.cs
Labels: testing

#170 Seed mmdetection
  DAL/ApplicationStorage/SeedDatabase/ConfigJsonFiles/TrainingAndDetectionProcessSeedDatabaseAndFiles.json
  DAL/ApplicationStorage/SeedDatabase/DbInitializer.cs
  DAL/ApplicationStorage/SeedDatabase/ModulesConfigs/MMDetectionSetup/MMDetectionConfiguration.cs
  DAL/ApplicationStorage/SeedDatabase/ModulesConfigs/MMDetectionSetup/MMDetectionSetupService.cs
  DAL/DAL.csproj
  MainApp.MVC/Areas/IntranetPortal/Controllers/TrainedModelsController.cs
  MainApp.MVC/Program.cs
  MainApp.MVC/appsettings.Development.json
  MainApp.MVC/appsettings.Production.json
  MainApp.MVC/appsettings.Staging.json
  MainApp.MVC/appsettings.json
  SD/Helpers/CommonHelper.cs
  ins_development/scripts/large_image_annotated_inference.py
Labels: code improvement

#174 fix: fixing isCompleted property changing value for training run, fix…
  MainApp.BL/Services/TrainingServices/TrainingRunService.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/TrainingRunsController.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/TrainingRunsControllerTests.cs
Labels: bug

#179 Tests seed db
  MainApp.BL/Services/TrainingServices/TrainingRunService.cs
  Tests/DalTests/ApplicationStorage/SeedDatabase/ModuleConfigs/MMDetectionSetupServiceTests.cs
  Tests/MainAppBLTests/Services/TrainingServices/TrainingRunServiceTests.cs
Labels: testing

#183 test: x unit tests for mappers and view components
  Tests/MainAppBLTests/Mappers/ApplicationSettingsProfileBLTests.cs
  Tests/MainAppBLTests/Mappers/DatasetProfileBLTests.cs
  Tests/MainAppBLTests/Mappers/DetectionProfileBLTests.cs
  Tests/MainAppBLTests/Mappers/LegalLandfillManagementProfileBLTests.cs
  Tests/MainAppBLTests/Mappers/MapConfigurationProfileBLTests.cs
  Tests/MainAppBLTests/Mappers/TrainingProfileBLTests.cs
  Tests/MainAppBLTests/Mappers/UserManagementProfileBLTests.cs
  Tests/MainAppMVCTests/Mappers/DatasetProfileTests.cs
  Tests/MainAppMVCTests/Mappers/DetectionProfileTests.cs
  Tests/MainAppMVCTests/Mappers/MapConfigurationProfileTests.cs
  Tests/MainAppMVCTests/Mappers/TrainingProfileTests.cs
  Tests/MainAppMVCTests/ViewComponents/Map/DetectionIgnoreZonesToolViewComponentTests.cs
  Tests/MainAppMVCTests/ViewComponents/Map/DetectionInputImagesToolViewComponentTests.cs
  Tests/MainAppMVCTests/ViewComponents/Map/GoToCoordinatesToolViewComponentTests.cs
  Tests/MainAppMVCTests/ViewComponents/Map/HistoricDataViewComponentTests.cs
  Tests/MainAppMVCTests/ViewComponents/Map/LastExtentToolViewComponentTests.cs
  Tests/MainAppMVCTests/ViewComponents/Map/MapViewComponentTests.cs
  Tests/MainAppMVCTests/ViewComponents/Map/MeasureAreaToolViewComponentTests.cs
  Tests/MainAppMVCTests/ViewComponents/Map/MeasureLengthToolViewComponentTests.cs
  Tests/MainAppMVCTests/ViewComponents/Map/ZoomToExtentToolViewComponentTests.cs
Labels: testing

#185 Tests dal missing
  DAL/ApplicationStorage/SeedDatabase/DbInitializer.cs
  DAL/ApplicationStorage/SeedDatabase/ModulesConfigs/MMDetectionSetup/MMDetectionSetupService.cs
  DAL/Interfaces/Repositories/DatasetRepositories/IImageAnnotationsRepository.cs
  DAL/Repositories/DatasetRepositories/DatasetClassesRepository.cs
  DAL/Repositories/DatasetRepositories/DatasetImagesRepository.cs
  DAL/Repositories/DatasetRepositories/Dataset_DatasetClassRepository.cs
  DAL/Repositories/DatasetRepositories/DatasetsRepository.cs
  DAL/Repositories/DatasetRepositories/ImageAnnotationsRepository.cs
  DAL/Repositories/MapConfigurationRepositories/MapLayerGroupsConfigurationRepository.cs
  DAL/Repositories/MapConfigurationRepositories/MapLayersConfigurationRepository.cs
  Tests/DalTests/ApplicationStorage/SeedDatabase/DbInitializerTests.cs
  Tests/DalTests/ApplicationStorage/SeedDatabase/ModuleConfigs/MMDetectionSetupServiceTests.cs
  Tests/DalTests/Repositories/DatasetRepositories/DatasetsRepositoryTests.cs
  Tests/DalTests/Repositories/DatasetRepositories/ImageAnnotationsRepositoryTests.cs
  Tests/DalTests/SeedDbClasses/ImageAnnotationsSeedData.cs
  Tests/Fixtures/TestDatabaseFixture.cs
  Tests/MainAppBLTests/MMDetectionConfigurationServiceTests.cs
  Tests/MainAppBLTests/Services/ImageAnnotationsServiceTests.cs
  Tests/MainAppBLTests/Services/TrainingServices/TrainingRunServiceTests.cs
  Tests/SDTests/Helpers/CommonHelperTests.cs
Labels: testing

#187 Tests coco utils
  .github/workflows/deploy_selfhosted.yml
  MainApp.MVC/Areas/IntranetPortal/Controllers/DatasetsController.cs
  MainApp.MVC/Properties/PublishProfiles/Staging.pubxml
  MainApp.MVC/appsettings.Staging.json
  MainApp.MVC/web.Staging.config
  Tests/MainAppBLTests/Services/DatasetServices/CocoUtilsServiceTests.cs
Labels: testing

#193 tests: moooooore
  DAL/Repositories/DetectionRepositories/DetectedDumpSitesRepository.cs
  DAL/Repositories/DetectionRepositories/DetectionIgnoreZonesRepository.cs
  DAL/Repositories/LegalLandfillManagementRepositories/LegalLandfillPointCloudFileRepository.cs
  DAL/Repositories/LegalLandfillManagementRepositories/LegalLandfillRepository.cs
  DAL/Repositories/LegalLandfillManagementRepositories/LegalLandfillTruckRepository.cs
  DAL/Repositories/LegalLandfillManagementRepositories/LegalLandfillWasteImportRepository.cs
  DAL/Repositories/LegalLandfillManagementRepositories/LegalLandfillWasteTypeRepository.cs
  DAL/Repositories/TrainingRepositories/TrainedModelStatisticsRepository.cs
  DAL/Repositories/TrainingRepositories/TrainedModelsRepository.cs
  DAL/Repositories/TrainingRepositories/TrainingRunsRepository.cs
  MainApp.BL/Services/DetectionServices/DetectionRunService.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/AnnotationsController.cs
  MainApp.MVC/Helpers/JsonFileReader.cs
  Tests/DalTests/ApplicationStorage/SeedDatabase/DbInitializerTests.cs
  Tests/DalTests/Repositories/DatasetRepositories/ImageAnnotationsRepositoryTests.cs
  Tests/MainAppBLTests/Services/DetectionRunServiceTests.cs
  Tests/MainAppBLTests/UserManagementServiceTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/AnnotationsControllerTests.cs
Labels: testing

#194 tests: mmdetection service
  MainApp.BL/Interfaces/Services/IMMDetectionConfigurationService.cs
  Tests/MainAppBLTests/MMDetectionConfigurationServiceTests.cs
Labels: testing

#195 Fix coco utils
  MainApp.BL/Services/DatasetServices/CocoUtilsService.cs
  Tests/MainAppBLTests/MMDetectionConfigurationServiceTests.cs
  Tests/MainAppBLTests/Services/DatasetServices/CocoUtilsServiceTests.cs
  Tests/MainAppBLTests/Services/TrainingServices/TrainingRunServiceTests.cs
Labels: testing

#198 Multiple tests for Dataset , llWM, MapConfig, TrainedMOdels
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/DatasetClassesControllerTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/LegalLandfillWasteManagementControllerTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/MapConfigurationControllerTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/TrainedModelsControllerTests.cs
Labels: testing

#199 Docs revamp
  docs/docfx_project/documentation/toc.yml
  docs/docfx_project/guides/toc.yml
  docs/docfx_project/toc.yml
Labels: documentation

#201 tests: WE GOT 80% IN COBERTURA COVERAGE BABY
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/DetectionControllerTests.cs
Labels: testing
