Repository IntelligentNetworkSolutions/IllegalDumpSiteDetectionAndLandfillMonitoring, pull requests merged in 2024-04, with the labels that each got.

#38 Add auth filters
  DAL/Repositories/ApplicationSettingsRepository.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/AccountController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/SpecialActionsController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/UserManagementController.cs
  MainApp.MVC/Areas/IntranetPortal/Views/UserManagement/EditUser.cshtml
  MainApp.MVC/Filters/AuthClaimFilter.cs
  MainApp.MVC/Filters/TenantModuleFilter.cs
  MainApp.MVC/Helpers/AddClaimsForIntranetPortalUserHelper.cs
  MainApp.MVC/Helpers/ModulesAndAuthClaimsHelper.cs
  MainApp.MVC/Program.cs
  SD/Helpers/ClaimsPrincipalExtensions.cs
  Tests/DalTests/ApplicationSettingsDaTests.cs
  Tests/DalTests/Helpers/AppSettingsAccessorTests.cs
  Tests/DalTests/Helpers/ApplicationSettingsHelperTests.cs
  Tests/Fixtures/ConfigurationFixture.cs
  Tests/MainApp.MVC.Tests/Filters/AuthClaimFilterTests.cs
  Tests/MainApp.MVC.Tests/Filters/TenantModuleFilterTests.cs
  Tests/Tests.csproj
Labels: testing, code improvement

#41 refactor: dataset repositories code refactoring
  DAL/Interfaces/Repositories/DatasetRepositories/IDatasetClassesRepository.cs
  DAL/Interfaces/Repositories/DatasetRepositories/IDatasetImagesRepository.cs
  DAL/Interfaces/Repositories/DatasetRepositories/IDatasetsRepository.cs
  DAL/Interfaces/Repositories/DatasetRepositories/IImageAnnotationsRepository.cs
  DAL/Interfaces/Repositories/IBaseResultRepository.cs
  DAL/Repositories/BaseResultRepository.cs
  DAL/Repositories/DatasetRepositories/DatasetClassesRepository.cs
  DAL/Repositories/DatasetRepositories/DatasetImagesRepository.cs
  DAL/Repositories/DatasetRepositories/DatasetsRepository.cs
  DAL/Repositories/DatasetRepositories/ImageAnnotationsRepository.cs
  DTOs/MainApp.BL/DatasetDTOs/EditDatasetImageDTO.cs
  Dal/Interfaces/Repositories/DatasetRepositories/IDataset_DatasetClassRepository.cs
  Dal/Repositories/DatasetRepositories/Dataset_DatasetClassRepository.cs
  MainApp.BL/Interfaces/Services/DatasetServices/IDatasetClassesService.cs
  MainApp.BL/Interfaces/Services/DatasetServices/IDatasetImagesService.cs
  MainApp.BL/Interfaces/Services/DatasetServices/IDatasetService.cs
  MainApp.BL/Mappers/DatasetProfileBL.cs
  MainApp.BL/Services/DatasetServices/DatasetClassesService.cs
  MainApp.BL/Services/DatasetServices/DatasetImagesService.cs
  MainApp.BL/Services/DatasetServices/DatasetService.cs
  MainApp.BL/Services/DatasetServices/Dataset_DatasetClassService.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/AccountController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/DatasetClassesController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/DatasetImagesController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/DatasetsController.cs
  MainApp.MVC/Mappers/DatasetProfile.cs
  MainApp.MVC/ViewModels/IntranetPortal/Dataset/DatasetViewModel.cs
Labels: code improvement

#42 Test all n user management
  .github/workflows/dotnet-test.yml
  .gitignore
  DAL/Interfaces/Repositories/IUserManagementDa.cs
  DAL/Repositories/UserManagementDa.cs
  DTOs/MainApp.BL/UserDTO.cs
  Entities/ApplicationUser.cs
  ExcludeCodeCoverage.runsettings.xml
  MailSend/MailService.cs
  MainApp.BL/Interfaces/Services/IApplicationSettingsService.cs
  MainApp.BL/Interfaces/Services/IUserManagementService.cs
  MainApp.BL/Services/ApplicationSettingsService.cs
  MainApp.BL/UserManagementService.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/AccountController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/SpecialActionsController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/UserManagementController.cs
  MainApp.MVC/Helpers/AddClaimsForIntranetPortalUserHelper.cs
  MainApp.MVC/Helpers/DbResHtml.cs
  MainApp.MVC/Helpers/LocalizationQueryProvider.cs
  MainApp.MVC/Program.cs
  Tests/DTOsTests/MainAppBL/RoleManagementDTOTests.cs
  Tests/DTOsTests/MainAppBL/UserDTOTests.cs
  Tests/DTOsTests/MainAppBL/UserManagementDTOTests.cs
  Tests/DalTests/Repositories/UserManagementDaTests.cs
  Tests/EntitiesTests/ApplicationUserTests.cs
  Tests/MailSendTests/MailServiceTests.cs
  Tests/MainAppBLTests/LayoutServiceTests.cs
  Tests/MainAppBLTests/Services/ApplicationSettingsServiceTests.cs
  Tests/MainAppBLTests/UserManagementServiceTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/UserManagementControllerTests.cs
  Tests/MainAppMVCTests/Filters/AuthClaimFilterTests.cs
  Tests/MainAppMVCTests/Filters/TenantModuleFilterTests.cs
  Tests/MainAppMVCTests/Helpers/DbResHtmlTests.cs
  Tests/MainAppMVCTests/Mappers/UserManagementProfileTests.cs
  Tests/Tests.csproj
  WasteDetection.sln
  docs/docfx_project/development/testing.md
Labels: documentation, testing, code improvement

#47 add README and update docfx docs
  .gitignore
  README.md
  docs/docfx_project/about/code_of_conduct.md
  docs/docfx_project/about/intro.md
  docs/docfx_project/development/Set-up/server-set-up.md
  docs/docfx_project/development/intro.md
  docs/docfx_project/development/set-up.md
  docs/docfx_project/development/testing.md
  docs/docfx_project/development/toc.yml
  docs/docfx_project/diagrams/intro.md
  docs/docfx_project/diagrams/roadmap/roadmap-2024-03-04.png
  docs/docfx_project/diagrams/roadmap/roadmap.md
  docs/docfx_project/diagrams/toc.yml
  docs/docfx_project/index.md
  docs/docfx_project/test-ai-repo-intro-png.png
  docs/images/dataset-management-unannotated.png
  docs/images/detection-results-zoomed.jpg
  docs/images/logo-robot-formal.png
Labels: documentation

#50 open layers map helper tests
  Tests/MainAppMVCTests/Helpers/OpenLayersMapHelperTests.cs
Labels: testing

#52 fixing cropbox size, dataset class add button show and upload image e…
  MainApp.BL/Services/DatasetServices/DatasetImagesService.cs
  MainApp.MVC/Areas/IntranetPortal/Views/Datasets/Edit.cshtml
  MainApp.MVC/package-lock.json
Labels: bug

#54 feat: show historic data layer on map
  DTOs/DTOs.csproj
  DTOs/Helpers/GeoJsonHelper.cs
  DTOs/MainApp.BL/DetectionDTOs/DetectionRunsDTO.cs
  MainApp.MVC/Areas/IntranetPortal/Views/Map/Index.cshtml
  MainApp.MVC/ViewComponents/Map/HistoricDataViewComponent.cs
  MainApp.MVC/Views/Shared/Components/HistoricData/Default.cshtml
  MainApp.MVC/appsettings.json
  SD/AuthClaims.cs
  SD/Modules.cs
  Tests/SDTests/Classes/ModulesTests.cs
Labels: new feature

#56 refactor: organize dependencies
  MainApp.MVC/Infrastructure/Register/ApplicationServicesDependencyContainer.cs
  MainApp.MVC/Infrastructure/Register/InfrastructeServicesDependencyContainer.cs
  MainApp.MVC/Program.cs
Labels: code improvement

#60 Add detection run mvc
  .gitignore
  Entities/DetectionEntities/DetectionRun.cs
  MainApp.BL/Interfaces/Services/DetectionServices/IDetectionRunService.cs
  MainApp.BL/MainApp.BL.csproj
  MainApp.BL/Mappers/DetectionProfileBL.cs
  MainApp.BL/Mappers/UserManagementProfileBL.cs
  MainApp.BL/Services/DetectionServices/DetectionRunService.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/DetectionController.cs
  MainApp.MVC/Areas/IntranetPortal/Views/Datasets/Index.cshtml
  MainApp.MVC/Areas/IntranetPortal/Views/Detection/CreateDetectionRun.cshtml
  MainApp.MVC/Areas/IntranetPortal/Views/Shared/_Layout.cshtml
  MainApp.MVC/Areas/IntranetPortal/Views/Shared/_Sidebar.cshtml
  MainApp.MVC/MainApp.MVC.csproj
  MainApp.MVC/Program.cs
  MainApp.MVC/Views/Shared/_Layout.cshtml
  MainApp.MVC/wwwroot/css/site.css
Labels: new feature

#62 feat: Area comparison report added in historic data layer, detection run db
  DTOs/Helpers/GeoJsonHelper.cs
  DTOs/MainApp.BL/DetectionDTOs/DetectedDumpSiteDTO.cs
  DTOs/MainApp.BL/DetectionDTOs/DetectionRunsDTO.cs
  DTOs/MainApp.BL/DetectionDTOs/GroupedDumpSitesListHistoricDataDTO.cs
  DTOs/MainApp.BL/DetectionDTOs/HistoricDataLayerDTO.cs
  Dal/EnitityConfigurations/DetectionEntities/DetectedDumpSiteConfiguration.cs
  Dal/EnitityConfigurations/DetectionEntities/DetectionRunConfiguration.cs
  Dal/Interfaces/Repositories/DetectionRepositories/IDetectionRunsRepository.cs
  Dal/Repositories/DetectionRepositories/DetectionRunsRepository.cs
  MainApp.BL/Interfaces/Services/DetectionServices/IDetectionRunService.cs
  MainApp.BL/Services/DetectionServices/DetectionRunService.cs
  MainApp.MVC/Infrastructure/Register/ApplicationServicesDependencyContainer.cs
  MainApp.MVC/Infrastructure/Register/InfrastructeServicesDependencyContainer.cs
  MainApp.MVC/ViewComponents/Map/HistoricDataViewComponent.cs
  MainApp.MVC/Views/Shared/Components/HistoricData/Default.cshtml
Labels: new feature

#63 Project detetion results
  DTOs/Helpers/NewtonsoftJsonHelper.cs
  DTOs/ObjectDetection.API/Responses/DetectionRun/DetectionRunFinishedResponse.cs
  MainApp.BL/Interfaces/Services/DetectionServices/IDetectionRunService.cs
  MainApp.BL/MainApp.BL.csproj
  MainApp.BL/Services/DetectionServices/DetectionRunService.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/DetectionController.cs
  MainApp.MVC/Areas/IntranetPortal/Views/Detection/CreateDetectionRun.cshtml
  MainApp.MVC/Program.cs
  MainApp.MVC/appsettings.Development.json
  MainApp.MVC/appsettings.json
  docs/docfx_project/development/set-up.md
Labels: code improvement

#66 feat: detectionRunId as parameter and map focus on selected run
  DTOs/MainApp.BL/DetectionDTOs/HistoricDataDTO.cs
  Dal/Repositories/DetectionRepositories/DetectionRunsRepository.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/MapController.cs
  MainApp.MVC/Areas/IntranetPortal/Views/Map/Index.cshtml
  MainApp.MVC/ViewComponents/Map/HistoricDataViewComponent.cs
  MainApp.MVC/Views/Shared/Components/HistoricData/Default.cshtml
Labels: new feature

#67 Project detetion results
  MainApp.MVC/Areas/IntranetPortal/Controllers/DetectionController.cs
  MainApp.MVC/Areas/IntranetPortal/Views/Detection/CreateDetectionRun.cshtml
  MainApp.MVC/Areas/IntranetPortal/Views/Shared/_Layout.cshtml
  MainApp.MVC/web.config
  MainApp.MVC/wwwroot/css/site.css
  MainApp.MVC/wwwroot/js/site.js
Labels: bug

#69 feat: view detection runs, run as one layer, create detection run red…
  MainApp.BL/Interfaces/Services/DetectionServices/IDetectionRunService.cs
  MainApp.BL/Services/DetectionServices/DetectionRunService.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/DetectionController.cs
  MainApp.MVC/Areas/IntranetPortal/Views/Detection/CreateDetectionRun.cshtml
  MainApp.MVC/Areas/IntranetPortal/Views/Detection/DetectedZones.cshtml
  MainApp.MVC/Areas/IntranetPortal/Views/Shared/_Sidebar.cshtml
  MainApp.MVC/Mappers/DetectionProfile.cs
  MainApp.MVC/Program.cs
  MainApp.MVC/ViewComponents/Map/HistoricDataViewComponent.cs
  MainApp.MVC/ViewModels/IntranetPortal/Detection/DetectedDumpSiteViewModel.cs
  MainApp.MVC/ViewModels/IntranetPortal/Detection/DetectionRunViewModel.cs
  MainApp.MVC/Views/Shared/Components/HistoricData/Default.cshtml
  MainApp.MVC/appsettings.json
  SD/AuthClaims.cs
  SD/Modules.cs
  Tests/SDTests/Classes/ModulesTests.cs
Labels: new feature
