Repository IntelligentNetworkSolutions/IllegalDumpSiteDetectionAndLandfillMonitoring, pull requests merged in 2024-12, with the labels that each got.

#232 docs: map tools, users seed, scheduled runs, point clouds
  docs/docfx_project/documentation/landfill-management/3d-point-cloud.md
  docs/docfx_project/documentation/map/overview.md
  docs/docfx_project/documentation/scheduled-runs/overview.md
  docs/docfx_project/documentation/user-management/overview.md
Labels: documentation

#235 refactor: exception throws refactoring and other code parts
  DAL/Interfaces/Repositories/DetectionRepositories/IDetectionRunsRepository.cs
  DAL/Interfaces/Repositories/IUserManagementDa.cs
  DAL/Interfaces/Repositories/MapConfigurationRepositories/IMapConfigurationRepository.cs
  DAL/Repositories/DetectionRepositories/DetectionRunsRepository.cs
  DAL/Repositories/MapConfigurationRepositories/MapConfigurationRepository.cs
  DAL/Repositories/UserManagementDa.cs
  MainApp.BL/Interfaces/Services/DetectionServices/IDetectionRunService.cs
  MainApp.BL/Interfaces/Services/IUserManagementService.cs
  MainApp.BL/Interfaces/Services/MapConfigurationServices/IMapConfigurationService.cs
  MainApp.BL/Interfaces/Services/TrainingServices/ITrainedModelService.cs
  MainApp.BL/Services/DetectionServices/DetectionIgnoreZoneService.cs
  MainApp.BL/Services/DetectionServices/DetectionRunService.cs
  MainApp.BL/Services/LegalLandfillManagementServices/LegalLandfillPointCloudFileService.cs
  MainApp.BL/Services/LegalLandfillManagementServices/LegalLandfillService.cs
  MainApp.BL/Services/LegalLandfillManagementServices/LegalLandfillTruckService.cs
  MainApp.BL/Services/LegalLandfillManagementServices/LegalLandfillWasteImportService.cs
  MainApp.BL/Services/LegalLandfillManagementServices/LegalLandfillWasteTypeService.cs
  MainApp.BL/Services/MapConfigurationServices/MapConfigurationService.cs
  MainApp.BL/Services/MapConfigurationServices/MapLayerGroupsConfigurationService.cs
  MainApp.BL/Services/MapConfigurationServices/MapLayersConfigurationService.cs
  MainApp.BL/Services/TrainingServices/TrainedModelService.cs
  MainApp.BL/Services/TrainingServices/TrainingRunService.cs
  MainApp.BL/Services/TrainingServices/TrainingRunTrainParamsService.cs
  MainApp.BL/UserManagementService.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/AccountController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/DetectionController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/TrainingRunsController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/UserManagementController.cs
  MainApp.MVC/Areas/IntranetPortal/Views/Account/MyProfile.cshtml
  MainApp.MVC/Areas/IntranetPortal/Views/UserManagement/CreateUser.cshtml
  MainApp.MVC/Areas/IntranetPortal/Views/UserManagement/EditUser.cshtml
  MainApp.MVC/Areas/IntranetPortal/Views/UserManagement/Index.cshtml
  MainApp.MVC/ViewComponents/Map/MapViewComponent.cs
  MainApp.MVC/Views/Shared/Components/HistoricData/Default.cshtml
  Tests/DalTests/Repositories/MapConfigurationRepositories/MapConfigurationRepositoryTests.cs
  Tests/DalTests/Repositories/UserManagementDaTests.cs
  Tests/MainAppBLTests/Services/DetectionRunServiceTests.cs
  Tests/MainAppBLTests/Services/LegalLandfillPointCloudFileServiceTests.cs
  Tests/MainAppBLTests/Services/LegalLandfillServiceTests.cs
  Tests/MainAppBLTests/Services/LegalLandfillTruckServiceTests.cs
  Tests/MainAppBLTests/Services/LegalLandfillWasteImportServiceTests.cs
  Tests/MainAppBLTests/Services/MapConfigurationServiceTests.cs
  Tests/MainAppBLTests/Services/TrainingServices/TrainedModelServiceTests.cs
  Tests/MainAppBLTests/Services/TrainingServices/TrainingRunServiceTests.cs
  Tests/MainAppBLTests/UserManagementServiceTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/AccountControllerTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/DetectionControllerTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/TrainingRunsControllerTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/UserManagementControllerTests.cs
  Tests/MainAppMVCTests/ViewComponents/Map/MapViewComponentTests.cs
Labels: bug, testing, new feature, code improvement

#245 fix: x unit tests fixinig
  DTOs/ObjectDetection.API/MMDetectionConfiguration.cs
  MainApp.BL/Interfaces/Services/IMMDetectionConfigurationService.cs
  MainApp.BL/Services/DetectionServices/DetectionRunService.cs
  MainApp.BL/Services/MMDetectionConfigurationsService.cs
  MainApp.MVC/appsettings.Development.json
  MainApp.MVC/appsettings.Production.json
  MainApp.MVC/appsettings.Staging.json
  MainApp.MVC/appsettings.json
  Tests/DalTests/Repositories/MapConfigurationRepositories/MapConfigurationRepositoryTests.cs
  Tests/DalTests/Repositories/UserManagementDaTests.cs
  Tests/MainAppBLTests/Services/DetectionRunServiceTests.cs
Labels: bug, code improvement

#247 fix: annotate ,dataset is published
  DTOs/ObjectDetection.API/CocoTerminology.cs
  MainApp.BL/Services/DatasetServices/CocoUtilsService.cs
  MainApp.BL/Services/DatasetServices/DatasetClassesService.cs
  MainApp.BL/Services/DatasetServices/DatasetService.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/AnnotationsController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/DatasetsController.cs
  MainApp.MVC/Areas/IntranetPortal/Views/Annotations/Annotate.cshtml
  MainApp.MVC/Areas/IntranetPortal/Views/Datasets/Edit.cshtml
  MainApp.MVC/wwwroot/css/Datasets/editDataset.css
  MainApp.MVC/wwwroot/css/site.css
Labels: code improvement

#251 feat: trained model statistics, add delete dataset loader, adding add…
  MainApp.BL/Services/DatasetServices/DatasetService.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/DatasetsController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/DetectionController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/TrainedModelsController.cs
  MainApp.MVC/Areas/IntranetPortal/Views/ApplicationSettings/Index.cshtml
  MainApp.MVC/Areas/IntranetPortal/Views/AuditLogs/Index.cshtml
  MainApp.MVC/Areas/IntranetPortal/Views/DatasetClasses/Index.cshtml
  MainApp.MVC/Areas/IntranetPortal/Views/Datasets/Index.cshtml
  MainApp.MVC/Areas/IntranetPortal/Views/Detection/CreateDetectionRun.cshtml
  MainApp.MVC/Areas/IntranetPortal/Views/Detection/DetectedZones.cshtml
  MainApp.MVC/Areas/IntranetPortal/Views/Map/Index.cshtml
  MainApp.MVC/Areas/IntranetPortal/Views/Shared/_Sidebar.cshtml
  MainApp.MVC/Areas/IntranetPortal/Views/SpecialActions/Index.cshtml
  MainApp.MVC/Areas/IntranetPortal/Views/TrainingRuns/CreateTrainingRun.cshtml
  MainApp.MVC/Areas/IntranetPortal/Views/UserManagement/Index.cshtml
  MainApp.MVC/Helpers/HtmlHelpers.cs
  MainApp.MVC/wwwroot/css/site.css
  SD/AuthClaims.cs
  Tests/MainAppBLTests/Services/DatasetServiceTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/DatasetsControllerTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/DetectionControllerTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/TrainedModelsControllerTests.cs
Labels: bug, new feature, code improvement

#255 fix: fixing delete trained model to prevent deleting base trained mod…
  MainApp.BL/Services/TrainingServices/TrainingRunService.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/DetectionController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/TrainingRunsController.cs
  MainApp.MVC/Areas/IntranetPortal/Views/Shared/_Sidebar.cshtml
  Tests/MainAppBLTests/Services/DatasetServiceTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/TrainingRunsControllerTests.cs
Labels: code improvement

#258 refactor: try catch blocks added in controllers
  MainApp.BL/Services/ApplicationSettingsService.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/AccountController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/ApplicationSettingsController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/AuditLogsController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/DetectionIgnoreZonesController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/LegalLandfillsManagementController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/LegalLandfillsWasteManagementController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/MapConfigurationController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/ScheduleRunsController.cs
  MainApp.MVC/Areas/IntranetPortal/Controllers/TrainedModelsController.cs
  MainApp.MVC/appsettings.Development.json
  MainApp.MVC/appsettings.Production.json
  MainApp.MVC/appsettings.Staging.json
  MainApp.MVC/appsettings.json
  SD/AuthClaims.cs
  SD/Modules.cs
  Tests/MainAppBLTests/Services/ApplicationSettingsServiceTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/ApplicationSettingsControllerTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/AuditLogsControllerTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/LegalLandfillsManagementControllerTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/MapConfigurationControllerTests.cs
  Tests/MainAppMVCTests/Areas/IntranetPortal/Controllers/TrainedModelsControllerTests.cs
  Tests/SDTests/Classes/ModulesTests.cs
Labels: code improvement
